version: "3.2"

services:

    php:
        build:
            context: ./phpwsql
        depends_on:
            - sql
        networks:
            - fulp_vnet
        environment:
            - MYSQL_USER=root
            - MYSQL_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=fulptube
            - MYSQL_HOST=sql
        volumes:
            - ./www/:/var/www/html
            - ./www/dynamic/:/dynamic
        ports:
            - "80:80"
        container_name: fulpphp2
    
    sql:
        image: mysql:8.0.22
        networks:
            - fulp_vnet
        environment: 
            - MYSQL_ROOT_PASSWORD
            - MYSQL_DATABASE=fulptube
        volumes:
            - ./sqldata/:/var/lib/mysql
            - ./sqlinit/:/docker-entrypoint-initdb.d
        container_name: fulpsql2
    
    queuer:
        build:
            context: ./fulpqueue
        depends_on:
            - sql
        networks:
            - fulp_vnet
        environment:
            - MYSQL_USER=root
            - MYSQL_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=fulptube
            - MYSQL_HOST=sql
            - PYTHONUNBUFFERED=1
        volumes:
            - ./www/dynamic/:/dynamic
        container_name: fulpqueue2
    
    phpmyadmin:
        image: phpmyadmin
        depends_on:
            - sql
        networks:
            - fulp_vnet
        environment:
            - PMA_HOST=sql
            - PMA_PORT=3306
            - UPLOAD_LIMIT=300M
        ports:
            - "1337:80"
        container_name: fulpphpmyadmin2

networks:
    fulp_vnet:
